version: "3.8"
services:
    app:
        build:
            context: ./dockerConfig
            dockerfile: Dockerfile
        restart: "always"
        container_name: poupay-api
        ports:
          - "8070:80"
        volumes:
            - ./:/www/html
        links:
            - db

    db:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: "root"
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
volumes:
    dbdata:
