version: '3'

services:
    web:
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: poupay-backend
        ports:
            - "8074:80"
        volumes:
            - ./:/var/www/html
    db:
        image: mysql:8
        container_name: poupay-database
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=poupay
            - MYSQL_PASSWORD=root
        ports:
        - "3307:3306"
        volumes:
            - db:/var/lib/mysql

volumes:
    db:
