version: '3'
services:
  web:
    image: php:8.1-apache
    container_name: app-poupay-api
    ports:
      - "8070:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: